DROP TABLE IF EXISTS REGULAR_USER;

CREATE TABLE REGULAR_USER (
    user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    city VARCHAR(255),
    phone VARCHAR(255)
);